In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pyECLAT import ECLAT
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
#loading dataset
df=pd.read_csv('Market_Basket_Optimisation.csv', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#creating transactions list
transactions=[]
for i in range(0,7501):
    transactions.append([str(df.values[i, j]) for j in range(0,20)])

In [ ]:
#ECLAT model train
eclat = ECLAT(data=df)

# run algorithm
indices, support = eclat.fit(
    min_support=0.05,
    min_combination=2,
    max_combination=2
)

Combination 2 by 2

300it [00:01, 204.13it/s]

In [54]:
support.items()

dict_items([('eggs & mineral water', 0.05092654312758299), ('spaghetti & mineral water', 0.05972536995067324), ('chocolate & mineral water', 0.05265964538061592)])

In [52]:
df_rules=pd.DataFrame(list(support.items()), columns=['itemsets', 'support']).sort_values(by=['support'], ascending=False)
df_rules

                    itemsets   support
1  spaghetti & mineral water  0.059725
2  chocolate & mineral water  0.052660
0       eggs & mineral water  0.050927

In [49]:
from mlxtend.frequent_patterns import association_rules
rules=association_rules(df_rules, metric='confidence', min_threshold=0.02, support_only=True)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"frozenset({n, w, e, , i, r, a, t, l})",frozenset({m}),NaN,NaN,0.238368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"frozenset({n, w, e, , i, r, a, t, m})",frozenset({l}),NaN,NaN,0.238368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"frozenset({n, w, e, , i, r, a, l, m})",frozenset({t}),NaN,NaN,0.238368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"frozenset({n, w, e, , i, r, t, l, m})",frozenset({a}),NaN,NaN,0.238368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"frozenset({n, w, e, , i, a, t, l, m})",frozenset({r}),NaN,NaN,0.238368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86971,"frozenset({u, s})","frozenset({o, p})",NaN,NaN,0.050527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86972,frozenset({o}),"frozenset({u, p, s})",NaN,NaN,0.050527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86973,frozenset({p}),"frozenset({o, u, s})",NaN,NaN,0.050527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86974,frozenset({u}),"frozenset({o, p, s})",NaN,NaN,0.050527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86975,frozenset({s}),"frozenset({o, p, u})",NaN,NaN,0.050527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# FPGrowth & Association Rules

In [ ]:
te=TransactionEncoder()
df=pd.DataFrame(te.fit_transform(transactions), columns=te.columns_)
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
from collections import defaultdict
item_to_transactions=defaultdict(set)
item_to_transactions

defaultdict(set, {})

In [ ]:
for tx_id, items in enumerate(transactions):
    for item in items:
        item_to_transactions[item].add(tx_id)
for item, tx_id in item_to_transactions.items():
    print(f"{item}: {tx_id}")

shrimp: {0, 6147, 6149, 4108, 6156, 6158, 16, 2064, 6163, 20, 23, 4120, 2078, 4127, 6175, 4132, 2089, 2096, 2101, 2104, 4152, 4154, 69, 4168, 6219, 2124, 2134, 91, 107, 108, 2155, 110, 2159, 6251, 2170, 2172, 125, 6270, 2177, 2178, 6275, 6279, 142, 143, 4244, 149, 2197, 153, 155, 6302, 160, 2208, 164, 4264, 6318, 4274, 181, 2233, 2236, 4288, 2241, 2243, 6341, 199, 2252, 2261, 4317, 222, 4321, 4325, 236, 2292, 4343, 2297, 6400, 2308, 4359, 6409, 269, 2319, 273, 4377, 2334, 290, 6438, 6439, 6446, 2356, 2358, 4407, 2365, 6468, 2373, 328, 2381, 2383, 6486, 4440, 2393, 6492, 349, 4452, 2409, 373, 4471, 6522, 380, 2429, 6529, 390, 4493, 6543, 6553, 2480, 433, 6577, 2485, 6582, 6589, 4543, 6595, 6597, 455, 6600, 460, 461, 2509, 468, 469, 471, 474, 477, 479, 4582, 6630, 6643, 503, 505, 507, 6655, 6673, 6684, 6697, 6702, 6704, 565, 2615, 2617, 2618, 6715, 6716, 6717, 6719, 2632, 2635, 2637, 6749, 4704, 610, 4709, 4711, 2667, 620, 2669, 6766, 6775, 633, 2694, 2695, 6793, 656, 659, 662, 664, 4760, 666, 4765, 675, 6824, 2733, 2739, 694, 2744, 697, 2745, 699, 2758, 6855, 2760, 726, 4829, 2782, 741, 4838, 744, 2795, 4844, 6898, 2807, 762, 2810, 4860, 2818, 771, 2819, 4880, 788, 4890, 795, 800, 808, 4906, 811, 6955, 4913, 4920, 825, 827, 4924, 6972, 2878, 2883, 4931, 4932, 4935, 6983, 4937, 6985, 6989, 2895, 6998, 7001, 7004, 873, 2924, 2933, 888, 890, 4987, 4992, 897, 900, 4996, 4997, 906, 915, 5012, 7062, 5015, 5018, 936, 941, 946, 949, 2997, 5052, 3005, 958, 5054, 5061, 7109, 5067, 7115, 975, 7123, 3028, 983, 7127, 7130, 5083, 991, 3040, 5091, 996, 5100, 3058, 5106, 5113, 1026, 3084, 1037, 3088, 1049, 1058, 1059, 3109, 5162, 1072, 7217, 3123, 5180, 5182, 1092, 7245, 1108, 1113, 7258, 5215, 7264, 1122, 5218, 1136, 3186, 1144, 3194, 3196, 5244, 5246, 5275, 5276, 7323, 5280, 7330, 3239, 3241, 7343, 5301, 3255, 1208, 3259, 1213, 3261, 5310, 1216, 5311, 3268, 7364, 1225, 7369, 1234, 1246, 5347, 7398, 1261, 3310, 7412, 5368, 1277, 3334, 5384, 7434, 1292, 5394, 7442, 5399, 3353, 7449, 5403, 7450, 3359, 3368, 3369, 7467, 1326, 5422, 1328, 3377, 7474, 7479, 7481, 5439, 1345, 5446, 3399, 5447, 7494, 5451, 3411, 5459, 1365, 3414, 5465, 1374, 3423, 5478, 1388, 5486, 1392, 5490, 1398, 3446, 3447, 1407, 3457, 1417, 1421, 5518, 3480, 3492, 5541, 5551, 1459, 3508, 3517, 1470, 1471, 1476, 1479, 3527, 3529, 3543, 3551, 5604, 3558, 3559, 1512, 5606, 1514, 1526, 3575, 3578, 1530, 3584, 1537, 3589, 5638, 5647, 5648, 3604, 1557, 5662, 3615, 3628, 1585, 3642, 5696, 5697, 5698, 1604, 1605, 1606, 1607, 3659, 5707, 1614, 3666, 5719, 5722, 5731, 3685, 3692, 3695, 5745, 5747, 1656, 1667, 5764, 3722, 3723, 1682, 5780, 3735, 5784, 5791, 1699, 1701, 1704, 3753, 3754, 5802, 3759, 1713, 5810, 1716, 1725, 1740, 5837, 1748, 5854, 1760, 1778, 3828, 1783, 1784, 5894, 1807, 5907, 3863, 1816, 3868, 3871, 3876, 5925, 3879, 1834, 5942, 3895, 5945, 3900, 1856, 3905, 3912, 5969, 5971, 1878, 1879, 3927, 5980, 1885, 1893, 5990, 5991, 1898, 3950, 6021, 6026, 3980, 6035, 1940, 3990, 1947, 1958, 6058, 6059, 4012, 6060, 1977, 1985, 4034, 6083, 6085, 1992, 2001, 6100, 6102, 2007, 6103, 4067, 4073, 4075, 4076, 2033, 4089, 4090, 4094, 4095}
almonds: {0, 3588, 521, 6155, 6667, 5645, 528, 534, 2070, 3608, 544, 1570, 1574, 4649, 6697, 3116, 4142, 1584, 4145, 6195, 565, 4669, 6719, 4673, 6209, 6721, 1607, 2632, 6739, 7252, 3157, 1111, 3676, 94, 3166, 5217, 2148, 101, 102, 5734, 105, 5235, 118, 3711, 5759, 6275, 3716, 4741, 5252, 4236, 3213, 5778, 6813, 5280, 680, 6824, 3246, 7346, 691, 2739, 5814, 699, 707, 5831, 2255, 5839, 3283, 727, 1751, 730, 6876, 6877, 5854, 7398, 2794, 1774, 4337, 2803, 4852, 4348, 253, 1278, 3837, 4873, 5897, 6412, 781, 276, 788, 4374, 5396, 7444, 4378, 3869, 7453, 7454, 2850, 5922, 5930, 5421, 6449, 826, 4925, 3913, 1866, 3914, 2898, 4956, 7010, 4964, 6501, 2406, 872, 7019, 881, 1394, 4977, 1908, 2423, 3453, 2942, 3457, 6536, 1422, 2450, 6547, 5014, 1945, 1946, 3482, 414, 1442, 936, 1973, 3510, 952, 1468, 7105, 4042, 6091, 2510, 2513, 4050, 467, 6105, 3040, 3562, 4077, 4591, 4592, 6129, 6641, 1018}
avocado: {0, 4609, 3, 5128, 1033, 3082, 7180, 4113, 23, 1048, 25, 4632, 5661, 31, 2595, 1574, 5671, 2600, 1578, 5675, 1580, 45, 2606, 3116, 48, 5681, 4660, 3640, 5689, 5179, 3132, 6717, 1086, 4670, 4671, 2113, 67, 1092, 1604, 6725, 5704, 1611, 2635, 1613, 4683, 1615, 5195, 5199, 597, 2651, 2653, 5725, 1120, 5217, 7266, 5219, 3174, 3686, 4198, 4713, 4202, 107, 4714, 621, 7276, 623, 1139, 7283, 7285, 4216, 1146, 4219, 5757, 5760, 2694, 3719, 4231, 6283, 4236, 141, 653, 6799, 5778, 4243, 1685, 2710, 1687, 1690, 5786, 2204, 1181, 158, 2720, 3745, 4259, 5283, 166, 1707, 6828, 6319, 7343, 5809, 691, 1715, 2739, 4278, 3767, 5304, 4795, 7355, 2753, 2754, 3267, 3779, 2759, 4296, 1226, 1740, 1742, 4303, 3281, 3793, 6874, 5339, 1762, 2276, 229, 7396, 1771, 4331, 6381, 1774, 5361, 2290, 4344, 4858, 4349, 770, 5380, 6405, 1289, 2314, 2826, 780, 3339, 3855, 4371, 3349, 795, 4894, 5918, 803, 5923, 293, 807, 5928, 5929, 6952, 3374, 3375, 6958, 4402, 3899, 2876, 2877, 2370, 5442, 4420, 5443, 1863, 842, 2379, 1356, 333, 3406, 4941, 5966, 6474, 339, 3414, 2395, 860, 353, 1889, 4452, 5478, 5994, 5996, 4979, 7029, 886, 1398, 3448, 6008, 890, 6009, 1917, 2942, 2951, 6024, 1420, 1421, 2445, 6033, 5012, 5016, 928, 7072, 4515, 2468, 4004, 934, 5541, 2473, 1450, 4527, 2993, 1970, 948, 1975, 4024, 2489, 3002, 4535, 1468, 957, 6079, 4037, 4549, 5062, 6597, 5068, 2509, 2513, 1490, 7125, 3032, 4568, 6616, 5603, 2533, 4586, 4075, 4592, 5618, 1525, 3062, 3063, 5628, 1023}
vegetables mix: {0, 3073, 1540, 4612, 7174, 4110, 2576, 529, 7192, 4122, 6175, 3624, 4648, 1066, 3627, 1581, 5166, 2095, 7215, 4146, 6706, 7218, 5685, 5174, 6200, 6712, 4667, 7228, 5694, 6718, 6719, 7231, 7232, 1091, 2627, 6216, 4181, 5205, 1623, 3159, 1113, 3676, 1120, 1632, 2662, 1133, 1648, 3188, 2679, 6775, 4222, 2688, 641, 4226, 4227, 6273, 2184, 657, 4241, 151, 6809, 7322, 3740, 3741, 3232, 5284, 5799, 1704, 3241, 1706, 1707, 685, 2223, 5809, 7347, 4277, 7349, 6327, 3768, 4793, 1724, 6847, 3777, 7362, 6339, 717, 210, 7379, 4310, 6872, 2265, 4321, 6370, 3301, 4838, 234, 5357, 5361, 2802, 4852, 245, 6906, 2301, 4861, 5888, 1281, 6922, 779, 2836, 5396, 1815, 6425, 1822, 3871, 1315, 6947, 6439, 810, 3371, 6445, 2863, 1328, 7474, 6963, 2868, 4923, 3900, 5953, 5452, 2895, 5969, 338, 853, 3420, 1886, 2400, 2407, 7016, 6514, 4467, 4983, 5497, 2430, 3971, 2436, 905, 5002, 7054, 1423, 2455, 408, 5016, 6041, 7066, 6046, 2463, 4516, 5540, 3496, 5034, 6570, 6060, 943, 2480, 6578, 7095, 6589, 4542, 5054, 5566, 6079, 6087, 5576, 7114, 6605, 4558, 3538, 2515, 3540, 4050, 6612, 2519, 2520, 3032, 3034, 5089, 4077, 4590, 3567, 4591, 3061, 5109, 3071}
green grapes: {0, 2688, 3589, 4998, 5254, 7303, 905, 6667, 2700, 1294, 528, 6928, 3346, 5522, 6034, 3353, 6010, 6815, 7070, 4773, 3494, 3241, 554, 1450, 5759, 2480, 3505, 3634, 307, 1972, 4020, 5937, 1848, 3514, 1595, 4923, 2243, 6469, 1862, 6087, 7114, 1739, 3150, 1875, 3285, 472, 1016, 2392, 3032, 6363, 7133, 1886, 5214, 1120, 7391, 2148, 357, 3686, 6250, 107, 7276, 237, 3310, 3953, 3445, 632, 250, 3711}
whole weat flour: {0, 1796, 3718, 2824, 1033, 2952, 3338, 3339, 3593, 1558, 6166, 5912, 1819, 3995, 7070, 3872, 6055, 4136, 6314, 2348, 1838, 6395, 1200, 6960, 1332, 2740, 2046, 3895, 4152, 5684, 5438, 1087, 1856, 2113, 4544, 4163, 6080, 1989, 1862, 3913, 3921, 7380, 4057, 1882, 3802, 6234, 1120, 1888, 1634, 4320, 6241, 3582, 5990, 1513, 1258, 5354, 1900, 3949, 1646, 4847, 5739, 5747, 6388, 1781, 1526, 2424, 1145, 1787, 1918, 5759}
yams: {0, 5129, 3087, 29, 2042, 5155, 1575, 5162, 1595, 572, 5201, 603, 611, 1124, 621, 5234, 4216, 5753, 1152, 2690, 5252, 146, 663, 6811, 5791, 160, 673, 675, 5283, 6822, 170, 6827, 689, 691, 699, 4798, 7368, 5851, 738, 227, 5347, 229, 2792, 6890, 5874, 6901, 5366, 1274, 5899, 2835, 6419, 4382, 807, 304, 307, 5434, 5437, 5950, 5965, 340, 2900, 2921, 368, 6001, 375, 6008, 3965, 5507, 5509, 2950, 2953, 906, 4499, 916, 432, 6068, 6079, 6081, 462, 6608, 7131, 5602, 2041, 5626, 5627, 1021}
cottage cheese: {0, 3587, 6660, 5639, 4617, 3082, 1547, 6674, 4118, 2071, 4124, 541, 5661, 4129, 4642, 3620, 38, 2599, 3629, 3630, 6705, 2613, 4661, 3640, 2617, 4152, 5689, 2625, 1090, 3649, 5702, 7240, 4683, 1612, 1613, 7245, 5199, 1618, 1110, 1626, 3162, 3676, 1120, 4192, 3683, 5220, 102, 5224, 5739, 621, 625, 5234, 1653, 6262, 1655, 5755, 7292, 2685, 6782, 7294, 640, 5249, 6273, 5623, 6788, 5766, 1164, 5625, 5772, 7313, 3219, 2198, 4759, 3739, 6299, 2720, 3745, 1186, 7331, 5284, 4261, 5798, 3240, 2729, 4776, 1197, 174, 1711, 2733, 5294, 7342, 7347, 3253, 5304, 5306, 4284, 2238, 5825, 3267, 5827, 5831, 1225, 5835, 6860, 3279, 2259, 6867, 6361, 6873, 4315, 1761, 6370, 5347, 741, 3304, 4841, 5356, 3316, 1273, 6905, 5372, 5884, 6908, 6912, 7425, 4354, 1283, 7428, 1287, 1799, 2824, 3847, 3848, 5898, 5900, 782, 7434, 5905, 1298, 2836, 2841, 3865, 1820, 4893, 1822, 6430, 2338, 2851, 3877, 3377, 5425, 7473, 820, 821, 3899, 7483, 5441, 5954, 5447, 5961, 3918, 2383, 4430, 6990, 6482, 4436, 6486, 5979, 3932, 6491, 4959, 2404, 3949, 878, 879, 1902, 882, 3444, 2937, 2938, 6010, 2431, 4992, 7040, 1924, 4996, 1934, 3476, 6550, 3479, 5016, 3997, 2464, 417, 1441, 2979, 3494, 2984, 4522, 6570, 5036, 1456, 949, 7093, 6074, 3515, 6587, 2494, 447, 5056, 6085, 6087, 2505, 6604, 2510, 463, 4049, 5076, 5080, 3033, 3034, 4057, 6622, 481, 994, 503, 1512, 2025, 4077, 4590, 6644, 1527, 6648, 5113, 6650, 1019, 4092, 3069, 3071}
energy drink: {0, 7170, 6665, 7181, 5647, 5649, 2069, 6677, 5663, 4641, 1578, 557, 558, 1071, 1582, 3124, 3638, 4664, 5688, 58, 1082, 62, 4677, 1608, 7245, 4688, 85, 5210, 605, 3166, 4703, 1120, 6240, 6749, 2659, 5220, 5227, 622, 5747, 2676, 7292, 127, 1152, 1153, 642, 2177, 4753, 6801, 4755, 660, 2709, 3733, 3740, 2717, 6814, 4255, 1186, 1698, 7339, 1711, 2735, 2736, 3767, 4288, 3777, 6336, 4294, 2249, 202, 3790, 2767, 5329, 6866, 1748, 2772, 3288, 1754, 4319, 5855, 2785, 4833, 227, 1766, 4326, 2794, 5362, 6899, 2293, 7419, 6402, 6914, 263, 3335, 1801, 5897, 271, 6415, 6418, 6426, 4383, 3873, 2339, 2851, 1319, 1321, 6954, 6955, 1838, 5422, 304, 2864, 6446, 5431, 3897, 2874, 6458, 316, 2876, 6461, 2879, 6973, 4417, 5441, 7484, 3398, 5447, 2888, 3401, 842, 2891, 5449, 849, 2898, 3921, 4436, 5460, 343, 5976, 2908, 7005, 4447, 5471, 1889, 1384, 873, 2924, 2925, 5997, 879, 1392, 1393, 6003, 2933, 2424, 7034, 3964, 7037, 6020, 6533, 5510, 2951, 6539, 2968, 2969, 5016, 6553, 1437, 2974, 6559, 7069, 7077, 5543, 1448, 1966, 5550, 5551, 2483, 5556, 440, 441, 2493, 2497, 1986, 4043, 460, 2508, 6605, 2000, 4050, 5587, 7125, 6615, 7127, 2530, 6119, 1007, 3057, 1011, 5113, 7167}
tomato juice: {0, 6149, 4108, 5133, 3598, 5134, 6674, 2581, 5141, 4632, 540, 4125, 4636, 543, 6684, 548, 7205, 552, 3624, 4649, 1067, 7214, 1073, 5170, 5682, 3636, 7218, 6710, 5689, 1085, 2112, 580, 2117, 3652, 4165, 5190, 4683, 1612, 2124, 2637, 5707, 3153, 6229, 5209, 602, 3162, 3580, 5724, 3167, 1120, 1632, 6241, 5731, 2148, 5732, 3686, 4710, 6243, 6752, 111, 2673, 3187, 5235, 7285, 118, 1655, 7286, 1661, 638, 3197, 1152, 6273, 2691, 134, 3719, 2184, 137, 6791, 139, 5772, 6795, 2197, 3734, 2711, 6810, 2204, 5276, 2718, 5282, 7330, 166, 1191, 7334, 682, 1706, 7342, 5295, 6832, 2740, 5300, 189, 702, 3778, 6850, 2248, 722, 3283, 3794, 5333, 220, 5853, 4838, 6374, 236, 5356, 3313, 4339, 1782, 3323, 5885, 5375, 256, 259, 4355, 5381, 776, 7434, 5388, 5389, 5392, 4887, 5403, 5922, 294, 806, 3878, 297, 4390, 6438, 300, 6439, 3886, 303, 816, 4910, 819, 2357, 7477, 3900, 317, 6973, 3904, 4416, 4929, 4931, 324, 5954, 5955, 3912, 841, 6987, 3920, 6492, 350, 1896, 2921, 362, 4458, 364, 5481, 1903, 4975, 373, 5495, 393, 4489, 6028, 5005, 6029, 4496, 3990, 6040, 5529, 6041, 3995, 421, 3493, 4009, 1964, 5557, 6581, 7093, 6073, 1978, 3514, 6590, 1472, 6080, 6594, 1476, 1988, 6596, 7110, 6088, 1482, 973, 6098, 2006, 6102, 6614, 476, 2524, 992, 6112, 4578, 6626, 999, 1511, 1513, 1514, 7144, 2028, 3057, 5621, 4086, 3063, 4090, 1532}
low fat yogurt: {0, 4097, 2052, 5, 16, 6164, 2071, 2078, 4126, 6184, 2105, 6207, 4163, 6214, 4167, 6216, 76, 6221, 2126, 2134, 87, 89, 90, 92, 6237, 2143, 4199, 108, 112, 6257, 6259, 6262, 6264, 125, 2173, 2174, 2175, 4230, 4231, 2185, 2186, 6282, 2189, 2190, 4241, 6291, 2202, 6299, 6302, 2207, 2208, 163, 4262, 169, 2217, 4267, 6319, 6337, 2243, 201, 6350, 6353, 2267, 6368, 235, 241, 2303, 2304, 4352, 4355, 4356, 4357, 2312, 4363, 6411, 270, 2321, 4369, 6420, 4374, 4377, 2330, 6430, 4386, 6437, 294, 6438, 300, 2355, 2357, 6453, 6460, 320, 4420, 6468, 6472, 4428, 2381, 2382, 6489, 2405, 6502, 4457, 6505, 2411, 2413, 6515, 6525, 6526, 4482, 4489, 395, 2443, 2448, 405, 411, 419, 2471, 2472, 6569, 426, 4522, 2477, 6577, 2482, 4546, 2499, 456, 460, 462, 463, 467, 4565, 4570, 6618, 476, 4573, 4575, 482, 4590, 501, 502, 511, 2570, 523, 2578, 538, 4635, 2589, 6685, 543, 2595, 553, 554, 555, 2601, 2613, 570, 4671, 4677, 4678, 584, 2632, 4680, 4684, 6738, 4692, 2645, 601, 4698, 6745, 6746, 6747, 2654, 608, 2662, 2664, 2667, 4717, 626, 6770, 638, 4735, 640, 4737, 6786, 643, 2691, 646, 654, 656, 4752, 4753, 661, 6805, 4760, 4762, 668, 4765, 6812, 4774, 679, 682, 4779, 6831, 6836, 6838, 695, 6839, 2746, 4794, 4798, 2751, 2752, 6846, 6850, 709, 714, 6859, 2764, 4812, 718, 2766, 4814, 721, 2770, 4815, 4820, 6869, 730, 2780, 733, 2786, 4834, 2791, 2792, 2798, 751, 4847, 4848, 4850, 2803, 756, 757, 758, 759, 2807, 4852, 4858, 4870, 777, 778, 779, 2825, 4877, 6924, 4892, 6944, 4898, 805, 4902, 6957, 814, 4915, 4920, 4929, 2884, 2885, 841, 842, 6988, 853, 857, 4954, 7004, 7011, 871, 4972, 4974, 4975, 2928, 4977, 4979, 4987, 4991, 896, 7047, 5011, 5028, 5029, 935, 940, 7088, 5043, 7104, 5060, 7110, 5069, 5070, 7119, 5072, 7120, 980, 7125, 7128, 7131, 7132, 990, 3046, 3047, 1004, 5110, 5113, 1019, 1027, 3077, 3079, 3080, 7177, 5131, 7188, 1045, 7192, 1050, 7202, 7203, 1060, 3115, 5167, 1072, 7218, 1076, 1078, 3126, 5175, 3133, 7232, 5185, 5190, 7240, 1099, 1120, 3176, 7286, 5241, 5250, 3209, 5262, 5267, 7316, 5275, 1195, 1196, 7344, 7345, 5306, 3260, 3262, 3265, 3272, 1225, 1226, 5334, 1242, 3290, 1248, 7395, 3300, 1255, 1256, 1257, 1258, 3305, 7404, 3309, 7409, 5365, 7420, 1279, 5375, 7426, 1285, 3334, 7432, 7433, 7441, 7442, 3347, 5395, 7443, 5415, 7464, 7465, 7479, 5438, 7490, 1349, 1354, 7500, 3414, 1368, 1373, 1377, 1378, 5474, 3432, 5483, 1388, 5484, 1392, 1401, 5498, 3454, 5505, 3460, 5511, 3482, 3484, 5535, 3493, 3494, 1448, 1452, 5550, 5560, 5565, 3519, 5568, 3522, 1477, 3527, 1480, 5582, 1489, 5592, 3545, 1502, 1504, 3559, 1518, 3571, 1525, 3574, 3576, 3579, 3582, 1537, 3590, 1545, 3603, 3607, 5657, 1571, 3619, 1579, 3628, 5676, 1585, 3635, 3638, 3642, 5691, 3645, 3647, 3652, 5700, 3660, 3663, 3671, 1624, 5721, 1655, 5751, 1660, 3711, 5759, 5762, 5765, 5771, 5786, 5796, 5799, 3756, 5805, 3762, 1715, 3764, 3782, 3786, 1745, 3795, 5843, 5844, 3799, 3800, 1753, 3803, 5854, 5858, 3812, 3813, 3815, 5863, 3825, 5873, 3834, 1787, 5884, 1796, 3844, 1798, 3849, 3851, 5901, 3855, 5907, 1813, 3866, 3867, 3871, 1827, 3877, 5926, 3884, 3885, 5933, 1839, 1843, 3893, 5942, 3908, 3913, 1866, 5963, 5969, 3923, 5976, 1881, 3929, 5977, 3937, 3938, 1891, 1894, 3945, 3946, 3954, 6014, 1919, 3972, 6027, 6032, 3985, 3988, 3993, 6041, 3996, 6057, 1977, 4033, 4034, 4035, 1988, 4042, 1996, 2003, 4053, 4061, 2021, 2023, 6119, 4080, 6135, 6136}

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

frequent_itemsets = fpgrowth( df, min_support=0.01, use_colnames=True)

print(frequent_itemsets.head())

    support          itemsets
0  0.238368   (mineral water)
1  0.132116       (green tea)
2  0.076523  (low fat yogurt)
3  0.071457          (shrimp)
4  0.065858       (olive oil)

In [ ]:
#frequent_itemsets.sort_values('support', ascending=True)

In [ ]:
from mlxtend.frequent_patterns import association_rules
rules=association_rules(frequent_itemsets, metric='confidence', min_threshold=0.02)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

                 antecedents      consequents   support  confidence      lift
0                      (nan)  (mineral water)  0.238235    0.238267  0.999574
1            (mineral water)            (nan)  0.238235    0.999441  0.999574
2                (green tea)  (mineral water)  0.031063    0.235116  0.986357
3            (mineral water)      (green tea)  0.031063    0.130313  0.986357
4                      (nan)      (green tea)  0.131982    0.132000  0.999124
...                      ...              ...       ...         ...       ...
1652  (mushroom cream sauce)            (nan)  0.019064    1.000000  1.000133
1653           (nonfat milk)            (nan)  0.010399    1.000000  1.000133
1654              (eggplant)            (nan)  0.013198    1.000000  1.000133
1655         (fromage blanc)            (nan)  0.013598    1.000000  1.000133
1656                (melons)            (nan)  0.011998    1.000000  1.000133

[1657 rows x 5 columns]

In [ ]:
top_itemsets=frequent_itemsets.head(5)
top_itemsets

    support          itemsets
0  0.238368   (mineral water)
1  0.132116       (green tea)
2  0.076523  (low fat yogurt)
3  0.071457          (shrimp)
4  0.065858       (olive oil)